site/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;

Route::get('/', function () {
    return view('welcome');
})->name("accueil");

Auth::routes();

Route::resource("/article", "ArticleController");


Route::get('/afficherOffre/{idOffre}', "OffreEmploiController@AfficherOffre")->name('offre');

Route::get('/offreEmploiDispo', "OffreEmploiController@listeOffres")->name("offresDispos");

//Admin
Route::prefix("/admin")->name("admin.")->group(function(){
    Route::get("/", "AdminController@index")->name("index");
    Route::prefix("/stats")->name("stats.")->group(function() {
        Route::get("/candidatures/", "AdminController@getStatsCandidatures")->name("candidatures");
        Route::get("/nombres/", "AdminController@getStatsNombres")->name("numbers");
    });

    Route::resource("categories", "CategorieController");

});

/**
*XAV
*/
//Route de test pour la page du compte
Route::get('Compte','CompteControleur@indexCompte')->name('compte');
//Route de test pour la page du compte
Route::get('ParametreCompte','CompteControleur@indexParam')->name('ParametreCompte');
//Route de test pour la page publique du compte -> determiner
//si on dirige vers la page compte publique ou vers
//la page compte normal avec une condition dans le controleur du compte normal
Route::get('AffichageComptePublique','CompteControleur@indexPublique')->name('ComptePublique');
Route::post('controleParametre','CompteControleur@parametre')->name('controleParametre');
Route::get('ParametreCompte/img/{avatar}.jpg','CompteControleur@avatar')->name('Avatar');


/**
*XAV
*/


Route::get("/migrateAndSeed", function(Request $request) {
    if ($request->pass != "PassAdmin123")
    {
        return redirect("/");
    }

    echo Artisan::call("migrate:refresh", ['--force' => true, "--seed" => true]);

});

// Rémi //

Route::get('/afficherCandidature/{$idCandidature}', "CandidatureController@afficherCandidature")->name('candidature');

Route::get('/listeCandidatures', "CandidatureController@listeCandidatures")->name('ListeCandidatures');

Route::get('/listeCandidaturesEmployeur', "CandidatureController@listeCandidaturesEmployeur")->name('listeCandidaturesEmp');

Route::post('/modifCandidature{$idCandidature}', "CandidatureController@modifCandidature")->name('modifCandidature');

Route::post('/modifEtatCandidature{$idCandidature}', "CandidatureController@modifEtatCandidature")->name('modifEtatCandidature');

Route::get('/afficheRecherche', "OffreEmploiController@afficheRecherche")->name('afficheRecherche');

Route::get('/rechercheOffreEmploi', "OffreEmploiController@rechercheOffreEmploi")->name('rechercheOffreEmploi');

//////////

Route::get('/offresEmployeur', "OffreEmploiController@listeOffresEmployeur");

Route::get('/afficherOffre/{idOffre}', "OffreEmploiController@afficherOffre")->name('offre');

Route::post('/creerOffreEmploi', "OffreEmploiController@creerOffreEmploi");

Route::get('/creerOffreEmploi', "OffreEmploiController@afficherCreationOffre")->name('creerOffre');

Route::post('/modifOffreEmploi/{idOffre}', "OffreEmploiController@modifOffreEmploi");

//Route de test pour le front
Route::get('testInterface','TestInterfaceController@index');


/**
*Route victor
*
*/

Route::get('/modifOffreEmploi/{idOffre}', "OffreEmploiController@afficherModifOffre")->name("modifOffre");

Route::get('/candidater/{idOffre}',"CandidatureController@afficherCreationCandidater")->name("candidature");

Route::post('/candidater/{idOffre}',"CandidatureController@candidaterOffre")->name("candidaturePost");

Route::get('/notifications',"CompteControleur@getListesInteraction")->name("notifications");

Route::get('/listeCandidates/{idOffre}',"CandidatureController@avoirListeCandidat")->name('listeCandi');

Route::post('/listeCandidates/{idOffre}',"CandidatureController@modifierEtat");

Route::get('/rechercher',"OffreEmploiController@rechercheOffreEmploi")->name("rechercher");


/*
*
*
*     ROUTES A MAEL !
*
*
*
*/
//Routes carte
Route::get('Carte/{type}','CarteController@index')->name("Carte");

Route::get('/offre/marqueur/{type}/{id?}','CarteController@getMarqueur')->name("offre.JSON");

Route::get('/Covoiturage', "CovoiturageController@index")->name("Covoiturage");

site/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('article.index') }}">Articles</a></li>
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

site/resources/views/layouts/template.blade.php
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="418 I'm a teampot">
    <title>{{$titre ?? "Handi Intérim"}}</title>

<link href="{{ url('/')}}/css/bootstrap.css" rel="stylesheet">
@section('style')
<link href="{{ url('/')}}/css/main.css" rel="stylesheet">
@show

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
    <nav class="header navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="{{route('accueil')}}">Handi Itérim</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {{Route::currentRouteName() === 'accueil' ? "active" : ""}}">
        <a class="nav-link" href="{{route('accueil')}}">Accueil</a>
      </li>
      <li class="nav-item {{Route::currentRouteName() === 'offresDispos' ? "active" : ""}}">
          <a class="nav-link" href="{{ route('offresDispos') }}">Offres d'emploi</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Cartes
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{route('Carte','Emploi')}}">Emploi</a>
          <a class="dropdown-item" href="{{route('Carte','Covoiturage')}}">Demande de transport</a>
      </li>
      @guest
          <li class="nav-item {{Route::currentRouteName() === 'login' ? "active" : ""}}">
              <a class="nav-link" href="{{ route('login') }}">Se connecter</a>
          </li>
      @else
        <li class="nav-item {{Route::currentRouteName() === 'compte' ? "active" : ""}}">
          <a class="nav-link" href="{{route('compte')}}">Mon compte</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('rechercher')}}">Rechercher</a>
        </li>
        <li class="nav-item {{Route::currentRouteName() === 'notifications' ? "active" : ""}}">
          <a class="nav-link" href="{{route('notifications')}}">Notifications</a>
        </li>
      @endguest
    </ul>
    <!-- <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn  my-2 my-sm-0" type="submit">Search</button>
  </form> -->
  </div>
</nav>
@yield('image')

<main role="main" class="ctnPrincipal container">

@yield('contenu')

</main>
@yield('nonImp')

<footer class="">
<p>Crazy Charly Day</p>
<p>418 i'm a teapot</p>
</footer>
<script src="{{ url('/')}}/js/jquerry.js" ></script>
<script src="{{ url('/')}}/js/bootstrap.bundle.min.js" ></script></body>
@yield('js')
</html>