site/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;

Route::get('/', function () {
    return view('welcome');
})->name("accueil");

Auth::routes();

Route::resource("/article", "ArticleController");


Route::get('/afficherOffre/{idOffre}', "OffreEmploiController@AfficherOffre")->name('offre');

Route::get('/offreEmploiDispo', "OffreEmploiController@listeOffres")->name("offresDispos");

//Admin
Route::prefix("/admin")->name("admin.")->group(function(){
    Route::get("/", "AdminController@index")->name("index");
    Route::prefix("/stats")->name("stats.")->group(function() {
        Route::get("/candidatures/", "AdminController@getStatsCandidatures")->name("candidatures");
        Route::get("/nombres/", "AdminController@getStatsNombres")->name("numbers");
    });

    Route::resource("categories", "CategorieController");

});

/**
*XAV
*/
//Route de test pour la page du compte
Route::get('Compte','CompteControleur@indexCompte')->name('compte');
//Route de test pour la page du compte
Route::get('ParametreCompte','CompteControleur@indexParam')->name('ParametreCompte');
//Route de test pour la page publique du compte -> determiner
//si on dirige vers la page compte publique ou vers
//la page compte normal avec une condition dans le controleur du compte normal
Route::get('AffichageComptePublique','CompteControleur@indexPublique')->name('ComptePublique');
Route::post('controleParametre','CompteControleur@parametre')->name('controleParametre');
Route::get('ParametreCompte/img/{avatar}.jpg','CompteControleur@avatar')->name('Avatar');


/**
*XAV
*/


Route::get("/migrateAndSeed", function(Request $request) {
    if ($request->pass != "PassAdmin123")
    {
        return redirect("/");
    }

    echo Artisan::call("migrate:refresh", ['--force' => true, "--seed" => true]);

});

// Rémi //

Route::get('/afficherCandidature/{$idCandidature}', "CandidatureController@afficherCandidature")->name('candidature');

Route::get('/listeCandidatures', "CandidatureController@listeCandidatures")->name('ListeCandidatures');

Route::get('/listeCandidaturesEmployeur', "CandidatureController@listeCandidaturesEmployeur")->name('listeCandidaturesEmp');

Route::post('/modifCandidature{$idCandidature}', "CandidatureController@modifCandidature")->name('modifCandidature');

Route::post('/modifEtatCandidature{$idCandidature}', "CandidatureController@modifEtatCandidature")->name('modifEtatCandidature');

Route::get('/afficheRecherche', "OffreEmploiController@afficheRecherche")->name('afficheRecherche');

Route::get('/rechercheOffreEmploi', "OffreEmploiController@rechercheOffreEmploi")->name('rechercheOffreEmploi');

//////////

Route::get('/offresEmployeur', "OffreEmploiController@listeOffresEmployeur");

Route::get('/afficherOffre/{idOffre}', "OffreEmploiController@afficherOffre")->name('offre');

Route::post('/creerOffreEmploi', "OffreEmploiController@creerOffreEmploi");

Route::get('/creerOffreEmploi', "OffreEmploiController@afficherCreationOffre")->name('creerOffre');

Route::post('/modifOffreEmploi/{idOffre}', "OffreEmploiController@modifOffreEmploi");

//Route de test pour le front
Route::get('testInterface','TestInterfaceController@index');


/**
*Route victor
*
*/

Route::get('/modifOffreEmploi/{idOffre}', "OffreEmploiController@afficherModifOffre")->name("modifOffre");

Route::get('/candidater/{idOffre}',"CandidatureController@afficherCreationCandidater")->name("candidature");

Route::post('/candidater/{idOffre}',"CandidatureController@candidaterOffre")->name("candidaturePost");

Route::get('/notifications',"CompteControleur@getListesInteraction")->name("notifications");

Route::get('/listeCandidates/{idOffre}',"CandidatureController@avoirListeCandidat")->name('listeCandi');

Route::post('/listeCandidates/{idOffre}',"CandidatureController@modifierEtat");

Route::get('/rechercher',"OffreEmploiController@rechercheOffreEmploi")->name("rechercher");


/*
*
*
*     ROUTES A MAEL !
*
*
*
*/
//Routes carte
Route::get('Carte/{type}','CarteController@index')->name("Carte");

Route::get('/offre/marqueur/{type}/{id?}','CarteController@getMarqueur')->name("offre.JSON");

Route::get('/Covoiturage', "CovoiturageController@index")->name("Covoiturage");

site/app/Candidature.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Candidature extends Model
{
    protected $table = 'candidatures';

    protected $fillable = ['offre_id', 'user_id', 'etat', 'depart', 'typeTransport'];

    public function offre()
    {
        return $this->belongsTo(OffreEmploi::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public function getDepartAttribute($depart){
        return $depart??$this->user->adressePerso;
    }
    
     public function getCreatedAtAttribute($date)
    {
        return Carbon::parse($date);
    }
}

site/app/OffreEmploi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class OffreEmploi extends Model
{
    protected $table = 'offre_emplois';
    protected $fillable = [
       'categorie_id', 'expiration', 'lieu', 'intitule', 'profilPosteCourt', 'profilPoste'
    ];

    public function employeur(){
        return $this->belongsTo(User::class, 'employeur_id');
    }

    public function categorie(){
        return $this->belongsTo(CategorieActivite::class, 'categorie_id');
    }

    public function candidatures(){
        return $this->hasMany(Candidature::class,'offre_id');
    }
    
    public function getDateExpirationAttribute($date)
    {
        return Carbon::parse($date);
    }
}

site/resources/views/candidater.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="{{ url('/')}}/css/candidater.css" rel="stylesheet">
@endsection

@section('contenu')
<div class="contenu row">
    <h1>Candidater pour l'annonce</h1>
    <h2>Rappel de l'offre :</h2>
    <div class="compact">
    <div class="offres col-12">
            <a href={{route('offre',['idOffre'=>$offre->id])}}><h3>{{$offre->intitule}}</h3></a>
        <div class="row">
        <div class=" col-sm-12 col-md-4">
            <p class="entreprise">{{$offre->employeur->nom ." ". $offre->employeur->prenom}}</p>
        </div>
        <div class=" col-sm-12 col-md-8">
            <p>{{$offre->profilPosteCourt}}</p>
        </div>
        </div>
        </div>
    </div>
</div>
<h3>Documents et informations nécessaires offre : </h3>
    <form method="post" action="{{route('candidaturePost',['idOffre'=>$offre->id])}}">
        {{ csrf_field() }}
         <input type="hidden" id ="valeurCompte" name="adresseUser" value="{{$adresse}}">

         <div class="form-group row">
             <div class="col-sm-2">
            <label id="formPerso" for="colFormLabel" class="col-form-label">Adresse de départ</label>
             </div>
             <div class="col-sm-4">
            <div class="custom-control custom-radio">
                  <input type="radio" id="customRadio4" name="profil" value="profil" class="custom-control-input" checked>
                  <label id="add" class="custom-control-label" for="customRadio4">Mon adresse </label>
            </div>
                <div class="custom-control custom-radio">
                  <input type="radio" id="customRadio5" name="lieu" value="perso" class="custom-control-input">
                  <label class="custom-control-label" for="customRadio5">Adresse personnalisé</label>

            </div>
        </div>
            <div class="col-sm-6">
              <input name="adressePerso" type="text" class="form-control" id="adresse" placeholder="" readonly>
            </div>
          </div>


        <div class="row">
        <legend class="col-form-label col-sm-2 pt-0">Mode de transport</legend>
       <div class="col-sm-10">
        <div class="custom-control custom-radio">
              <input type="radio" id="customRadio1" name="transport" value="aucun" class="custom-control-input" checked>
              <label class="custom-control-label" for="customRadio1">Aucun</label>
            </div>
            <div class="custom-control custom-radio">
              <input type="radio" id="customRadio2" name="transport" value="normal" class="custom-control-input">
              <label class="custom-control-label" for="customRadio2">Normal</label>

        </div>
        <div class="custom-control custom-radio">
              <input type="radio" id="customRadio3" name="transport" value="adapte" class="custom-control-input">
              <label class="custom-control-label" for="customRadio3">Adapté</label>

        </div>
        </div>
        </div>

        @if(isset($erreur))
           <h1>{{$erreur}}</h1>
        @endif
        <div class="col-sm-4">
        <button type="submit"class="btn btn-success">Candidader</button>
        </div>
    </form>
@endsection

@section('js')
<script src="{{ url('/')}}/js/candidater.js"></script>
@endsection

site/resources/views/carte.blade.php
@extends('layouts.template')

@section('style')
@parent
<link rel="stylesheet" href="{{ url('/')}}/js/leaflet/leaflet.css" />
@endsection
@section('contenu')
<div id="map" data-fetch-url="{{route('offre.JSON',$type)}}" style="height:400px;">
</div>
@endsection

@section('js')
  @parent
<script src="{{ url('/')}}/js/leaflet/leaflet.js"></script>
<script src='{{ url('/')}}/js/carte.js'></script>
@endsection

site/resources/views/compte.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="css/compteCss.css" rel="stylesheet">
@endsection

@section('contenu')
<h1>Mon Compte</h1>

  <div class="row">
      <div class="col-md-3">
          <div class="description col-md-6 shadow-lg p-3 mb-5 rounded">
            <img src="{{ url('/')}}/img/{{$usr->avatar}}.jpg" alt="photo de profil de {{$usr->prenom." ".$usr->nom}}">
            <div class="trait col-md-12"></div>
            <div class="col-md-12">Prenom : {{$usr->prenom}}</div>
            <div class="trait col-md-12"></div>
            <div class="col-md-12">Nom : {{$usr->nom}}</div>
            <div class="trait col-md-12"></div>
            <a href={{route('ParametreCompte')}}>
              <div class="col-md-12">parametre du compte</div>
            </a>
            <div class="trait col-md-12"></div>
          </div>
          <div class="publique col-md-6 shadow-lg p-3 mb-5 rounded" >
            <div class="col-md-12">
              <a href={{route('ComptePublique')}}>
                <p>voir page version publique</p>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-9">
          <div class="row">
            @foreach($nombres as $temp)
            <div class="article col-md-12  shadow-lg p-3 mb-5 bg-white rounded" >
              <p>article {{$temp}}</p>
            </div>
            @endForeach
          <div>
        </div>
    </div>
@endsection

site/resources/views/compteParam.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="css/compteCss.css" rel="stylesheet">
@endsection

@section('contenu')
<div id="fond1">
  <h1>Parametre de mon Compte</h1>
    <div class="row">
      <div class=" col-md-3">
        <img src="{{ url('/')}}/img/{{$usr->avatar}}.jpg" alt="photo de profil de {{$usr->prenom." ".$usr->nom}}">
      </div>
      <div class=" col-md-3">
      </div>
      <div class=" col-md-5">
        <button id=b2 type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">modifier image</button>
        <!-- creation du modal -->
        <div class="modal fade" id="myModal" role="dialog">
          <!-- boite de dialogue -->
         <div class="modal-dialog">

           <!-- contenu -->
           <div class="modal-content">
             <div class="modal-header">
               <h4 class="modal-title">choix d'image</h4>
             </div>
             <div class="modal-body">

               <div class="row">

               @foreach($tab as $temp)
                  <div class=img1>
                     <a href="ParametreCompte{{$temp}}">
                       <img src="{{$temp}}"  style="cursor:pointer;" />
                    </a>
                  </div>
               @endforeach

              </div>
              </div>
             <div class="modal-footer">
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
             </div>
           </div>

         </div>
        </div>


      </div>
      <div class="col-md-10">
        <form class="form" action="{{route('controleParametre')}}" method="post">
            {{ csrf_field() }}
          <!---->
          <div class="row">
            <div class="col-md-5">Prenom:
            </div>
            <div class="form-group col-md-7">
              {{$usr->prenom}}
              <input type="text" class="form-control" name="usrPrenom" placeholder={{$usr->prenom}}>
            </div>
            <div class="col-md-9"></div>
          </div>
          <div class="trait col-md-12"></div>

          <!---->
          <div class="row">
            <div class="col-md-5">Nom:
            </div>
            <div class="form-group col-md-7">
              {{$usr->nom}}
              <input type="text" class="form-control" name="usrNom" placeholder={{$usr->nom}} >
            </div>
            <div class="col-md-9"></div>
          </div>
          <div class="trait col-md-12"></div>

          <!---->
          <div class="row">
            <div class="col-md-5">email:
            </div>
            <div class="form-group col-md-7">
              {{$usr->email}}
              <input type="text" class="form-control" name="usrEmail" placeholder={{$usr->email}} >
            </div>
            <div class="col-md-9"></div>
          </div>
          <div class="trait col-md-12"></div>

          <!---->
          <div class="row">
            <div class="col-md-5">adresse Professionnel:
            </div>
            <div class="form-group col-md-7">
              {{$usr->adressePro}}
              <input type="text" class="form-control" name="usrAdressePro" placeholder={{$usr->adressePro}}>
            </div>
            <div class="col-md-9"></div>
          </div>
          <div class="trait col-md-12"></div>

          <!---->
          <div class="row">
            <div class="col-md-5">adresse Personnel:
            </div>
            <div class="form-group col-md-7">
              {{$usr->adressePerso}}
              <input type="text" class="form-control" name="usrAdressePerso" placeholder={{$usr->adressePerso}}>
            </div>
            <div class="col-md-9"></div>
          </div>
          <div class="trait col-md-12"></div>
        <!---->
        </div>
      </div>
      <div class="row">
        <div class="col-md-6  "></div>
        <button id=b1 type="submit" class="btn btn-primary" value="submit">enregistrer</button>
      </div>
    </form>
  </div>
</div>
@endsection

site/resources/views/covoiturage.blade.php
@extends('layouts.template')

@section('style')
@parent
<link href="{{ url('/')}}/css/covoit.css" rel="stylesheet">
@endsection
@section('contenu')
<div class="présentation">

  <div class="input-group">
    <input type="text" class="form-control" placeholder="Rechercher">
    <div class="input-group-append">
      <button class="btn btn-info" type="button" id="button-addon2">Rechercher</button>
      <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Trier par</button>
    </div>
  </div>
  <div class="gauche">
  @foreach($covoiturage as $cov)
  <section>
    <p>Nom : {{$cov->nom}} - Prénom : {{$cov->prenom}}<p>
      <p>Adresse perso : {{$cov->adressePerso}}</p>
  </section>
  @endforeach
@endsection

site/resources/views/creationOffre.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="{{ url('/')}}/css/creationOffre.css" rel="stylesheet">
@endsection

@section('contenu')
<h1>Creation d'une offre d'emploi à votre nom</h1>
<form class="form-group row" method="post" action="">
    {{ csrf_field() }}
    <div class="col-sm-12 col-md-6">
        <label for="input7" class="col-form-label">Date</label>
        <input name="expiration" class="form-control" type="date" required>
    </div>
    <div class="col-sm-12 col-md-6">
        <label for="input6" class=" col-form-label">Catégorie</label>
        <div class="form-group">
        <select name="categorie" class="custom-select" required>
          @foreach($categories as $temp)
            <option value="{{$temp->id}}">{{$temp->nom}}</option>
          @endforeach
        </select>
    </div>
  </div>
    <div class="col-sm-12 col-md-6">
    <label for="input1" class=" col-form-label">Adresse</label>
      <input  name="lieu" type="text" class="form-control" id="input1" placeholder="Lieu de travail" required>
    </div>
    <div class="col-sm-12 col-md-6">
    <label for="input2" class=" col-form-label">Intitule</label>
      <input name = "intitule" type="text" class="form-control" id="input2" placeholder="Intitulé du métier" required>
    </div>
    <div class="col-sm-12 col-md-6">
    <label for="input3" class=" col-form-label">Description rapide</label>
      <textarea class="form-control" name="profilPosteCourt" rows="10" cols="30" required></textarea>
    </div>
    <div class="col-sm-12 col-md-6">
    <label for="input4" class=" col-form-label">Description longue</label>
        <textarea class="form-control" name="profilPoste" rows="10" cols="30" required></textarea>
    </div>
    <div class="col-sm-12 col-md-6">
    <button class="btn btn-success col-md-6 col-sm-6" type="submit">Publier votre offre d'emploi</button>
    </div>
</form>

@endsection

site/resources/views/listeCandidat.blade.php
@extends('layouts.template')
@section('style')
    @parent

@endsection

@section('contenu')
    @if(count($offres) == 0)
        <h1>Personne n'a encore répondu à votre annonce</h1>
    @else
    <div class="row">
        <h1>Les personnes qui ont répondus à votre offre :</h1>
        @foreach($offres as $temp)
            <div class="col-md-6 col-sm-12">
                <h2>{{$temp->user->prenom. " " . $temp->user->nom}}</h2>
                <p>Etat : {{$temp->etat}}</p>
                <p>A postulé le : {{$temp->created_at->formatLocalized('%A %d %B %Y')}}</p>
                @if($temp->etat == "attente")
                <form method="post" action="">
                    {{ csrf_field() }}
                    <input type="hidden" value="{{$temp->user->id}}" name=idUser>
                    <button type="submit" name="etat" value="acceptee"  class="btn btn-success col-sm-12 col-md-6">Valider</button>
                </form>
                <form method="post" action="">
                    {{ csrf_field() }}
                    <input type="hidden" value="{{$temp->user->id}}" name=idUser>
                    <button name="etat" value="refusee" class="btn btn-danger col-sm-12 col-md-6">Refuer</button>
                </form>
                @elseif($temp->etat=="refusee")
                    <p>Vous avez refusé cette demande</p>
                @else
                    <p>Vous avez acceptée la demande</p>
                @endif
            </div>        
        @endforeach
    </div>
    @endif
@endsection

site/resources/views/modifOffreEmploi.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="{{ url('/')}}/css/creationOffre.css" rel="stylesheet">
@endsection
@section('contenu')
<h1></h1>
<h1>Modification de votre offre d'emploi</h1>
<form class="form-group row" method="post">
     {{ csrf_field() }}
    <div class="col-sm-12 col-md-6">
        <label for="input7" class="col-form-label">Date</label>
        <input class="form-control" type="date" value="{{$offre->date_expiration->format("Y-m-d")}}">
    </div>
    <div class="col-sm-12 col-md-6">
        <label for="input6" class=" col-form-label">Catégorie</label>
        <div class="form-group">
        <select name="categorie" class="custom-select">
            <option selected="selected" value="{{$offre->categorie->id}}">{{$offre->categorie->nom}}</option>
             @foreach($categories as $temp)
                <option value="{{$temp->id}}">{{$temp->nom}}</option>
            @endforeach    
        </select>
    </div>
  </div>
    <div class="col-sm-12 col-md-6">
    <label for="input1" class=" col-form-label">Adresse</label>
      <input  name="lieu" type="text" class="form-control" id="input1" placeholder="{{$offre->lieu}}">
    </div>
    <div class="col-sm-12 col-md-6">
    <label for="input2" class=" col-form-label">Intitule</label>
      <input name = "intitule" type="text" class="form-control" id="input2" placeholder="{{$offre->intitule}}">
    </div>
    <div class="col-sm-12 col-md-6">
    <label for="input3" class=" col-form-label">Description rapide</label>
      <textarea class="form-control" name="profilPosteCourt" rows="10" cols="30">{{$offre->profilPosteCourt}}</textarea>
    </div>
    <div class="col-sm-12 col-md-6">
    <label for="input4" class=" col-form-label">Description longue</label>
        <textarea class="form-control" name="profilPoste" rows="10" cols="30">{{$offre->profilPoste}}</textarea>
    </div>
    <div class="col-sm-12 col-md-6">
    <button class="btn btn-success col-md-6 col-sm-6" type="submit">Modifier votre offre d'emploi</button>
    </div>
</form>
@endsection

site/resources/views/notificationsCompte.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="{{ url('/')}}/css/notification.css" rel="stylesheet">
@endsection

@section('contenu')
<div class="row">
@if(count($candidature)!=0)
<h1 >Statut de vos candidatures :</h1>
<ul>
@foreach($candidature as $candid)
<div class="col-12">
    <li>
        <a href="{{route('offre',['idOffre' => $candid->offre_id])}}"><h3>{{$candid->offre->intitule}}</h3></a>
    <p>{{$candid->offre->profilPosteCourt}}</p>
    <p> Etat : {{$candid->etat}}</p>
    </li>
</div>
@endforeach
</ul>
@else
    <h1 class="col">Vous n'avez pas de candidatures</h1>
@endif
</div>
<div class="separation"></div>

<div class="row">
@if(count($offreEmple)!=0)
    <h1 class="col-12">Les offres d'emploi que vous avez crée :</h1>
@foreach($offreEmple as $offre)
    <div class="col-md-6 col-sm-12">
    <div class="col-12">
        <a href="{{route('offre',['idOffre'=>$offre->id])}}"><h1 class="col">{{$offre->intitule}}</h1></a>
        <p class="col-sm-12 col-md-6">Etat : {{$offre->etat}}</p>
        <p class="col-sm-12 col-md-6">Date expiration : {{$offre->date_expiration}}</p>
        <a href="{{route('listeCandi',['idOffre'=>$offre->id])}}"><button class="col-md-8 col-sm-12 btn btn-success">Consulter les réponses</button></a>
        <a href="{{route('modifOffre',['idOffre'=>$offre->id])}}"><button class="col-md-8 col-sm-12 btn btn-warning">Modifier l'offre</button></a>
    </div>
    </div>
@endforeach
@else
    <h1 class="col">Vous n'avez pas crée d'offres d'emploi</h1>
@endif
</div>
@endsection

site/resources/views/offre.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="{{ url('/')}}/css/offre.css" rel="stylesheet">
<link href="{{ url('/')}}/css/carte.css" rel="stylesheet">
<link rel="stylesheet" href="{{ url('/')}}/js/leaflet/leaflet.css" />
@endsection
@section('contenu')
<div class="row">
    <h1 class="col-12">{{$offre->intitule . "[". $offre->categorie->nom ."]"}}</h1>
    <h2 class="col-12">Cette offre est proposé par : {{$offre->employeur->nom . " ". $offre->employeur->prenom}}</h2>
    <p class="col-12">{{$offre->profilPoste}}</p>

    @if($offre->etat == "actif")
        <h3 class="col-12">Expire le {{$offre->date_expiration->formatLocalized('%A %d %B %Y')}}</h3>
        <div class ="col-md-6 col-sm-12 ok">
            <h3>L'annonce est disponible</h3>
            <a href={{route('candidature',['idOffre'=>$offre->id])}}><button class="btn btn-success">Candidater</button></a>
    </div>
    @else
        <div class ="col-md-6 col-sm-12 pasOk"><h3>L'annonce n'est plus disponible</h3></div>
    @endif
    <div class="col-md-6 col-sm-12">
        <h3 class="col-12 pt-3" id ="titreCarte">Position de l'entreprise</h3>
        <p class="col-12">Adresse : {{$offre->lieu}}  </p>
    </div>
    <div id="map" data-fetch-url="{{route('offre.JSON',array('Emploi', $offre->id))}}">
    </div>

</div>
@endsection
@section('js')
  @parent
<script src="{{ url('/')}}/js/leaflet/leaflet.js"></script>
<script src='{{ url('/')}}/js/carte.js'></script>
@endsection

site/resources/views/offreRecherche.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="css/rechercheOffre.css" rel="stylesheet">
@endsection
@section('contenu')
<div class="row">
<h1 class="col-md-8 col-sm-12">Offres d'emplois</h1>
<a class="ml-auto mr-auto col-md-4 col-sm-6"href="{{route('creerOffre')}}"><button class="btn btn-custom">Créer une offre d'emploi</button></a>
</div>
<div class="contenu row">
        @foreach($offres as $temp)

        <div  class="p-2 col-sm-12 col-md-6 d-flex ">
            <div class="offres w-100">
            <a href={{route('offre', ['idOffre'=> $temp->id])}}>
                <h2>{{$temp->intitule}}</h2></a>
            <p class="entreprise">Par : {{$temp->employeur->nom . " " . $temp->employeur->prenom}}</p>
            <p>{{$temp->profilPosteCourt}}</p>
            </div>
        </div>
    @endForeach
</div>
@endsection

site/resources/views/rechercher.blade.php
@extends('layouts.template')
@section('style')
    @parent
<link href="/css/recherche.css" rel="stylesheet">
@endsection

@section('contenu')
<h1>Effectuer une recherche sur l'intitulé d'une offre d'emploi</h1>
<form class="form-group" method="get">
    <input name="search" type="search" class="input-sm form-control" placeholder="Recherche">
    
    <button type="submit" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-eye-open"></span> Chercher</button>
</form>
<div class="row">
@if(count($res)==0)
    <h3>Rien ne correspond à votre recherche</h3>
@else
@foreach($res as $temp)
<div class="col-md-6 col-sm-12">
    <a href="{{route('offre',['idOffre'=>$temp->id])}}"><h3>{{$temp->intitule}}</h3></a>
    <p> Etat {{$temp->etat}}</p>
    </div>
@endforeach
@endif
</div>
    @endsection

site/resources/views/test.blade.php
@extends('layouts.template')

@section('contenu')
    <div class="jumbotron">
    <h1>Navbar example</h1>
    <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
    <a class="btn btn-lg btn-primary" href="" role="button">View navbar docs &raquo;</a>
  </div>

    @if(count($nombres) == 0)
        <h1>C'est vide!!</h1>
    @endif
    @foreach($nombres as $temp)
        <div class="jumbotron">
        <h1>Navbar example {{$temp}}</h1>
        <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
        <a class="btn btn-lg btn-primary" href="" role="button">View navbar docs &raquo;</a>
      </div>
    @endForeach
@endsection