site/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;

Route::get('/', function () {
    return view('welcome');
})->name("accueil");

Auth::routes();

Route::resource("/article", "ArticleController");


Route::get('/afficherOffre/{idOffre}', "OffreEmploiController@AfficherOffre")->name('offre');

Route::get('/offreEmploiDispo', "OffreEmploiController@listeOffres")->name("offresDispos");

//Admin
Route::prefix("/admin")->name("admin.")->group(function(){
    Route::get("/", "AdminController@index")->name("index");
    Route::prefix("/stats")->name("stats.")->group(function() {
        Route::get("/candidatures/", "AdminController@getStatsCandidatures")->name("candidatures");
        Route::get("/nombres/", "AdminController@getStatsNombres")->name("numbers");
    });

    Route::resource("categories", "CategorieController");

});

/**
*XAV
*/
//Route de test pour la page du compte
Route::get('Compte','CompteControleur@indexCompte')->name('compte');
//Route de test pour la page du compte
Route::get('ParametreCompte','CompteControleur@indexParam')->name('ParametreCompte');
//Route de test pour la page publique du compte -> determiner
//si on dirige vers la page compte publique ou vers
//la page compte normal avec une condition dans le controleur du compte normal
Route::get('AffichageComptePublique','CompteControleur@indexPublique')->name('ComptePublique');
Route::post('controleParametre','CompteControleur@parametre')->name('controleParametre');
Route::get('ParametreCompte/img/{avatar}.jpg','CompteControleur@avatar')->name('Avatar');


/**
*XAV
*/


Route::get("/migrateAndSeed", function(Request $request) {
    if ($request->pass != "PassAdmin123")
    {
        return redirect("/");
    }

    echo Artisan::call("migrate:refresh", ['--force' => true, "--seed" => true]);

});

// Rémi //

Route::get('/afficherCandidature/{$idCandidature}', "CandidatureController@afficherCandidature")->name('candidature');

Route::get('/listeCandidatures', "CandidatureController@listeCandidatures")->name('ListeCandidatures');

Route::get('/listeCandidaturesEmployeur', "CandidatureController@listeCandidaturesEmployeur")->name('listeCandidaturesEmp');

Route::post('/modifCandidature{$idCandidature}', "CandidatureController@modifCandidature")->name('modifCandidature');

Route::post('/modifEtatCandidature{$idCandidature}', "CandidatureController@modifEtatCandidature")->name('modifEtatCandidature');

Route::get('/afficheRecherche', "OffreEmploiController@afficheRecherche")->name('afficheRecherche');

Route::get('/rechercheOffreEmploi', "OffreEmploiController@rechercheOffreEmploi")->name('rechercheOffreEmploi');

//////////

Route::get('/offresEmployeur', "OffreEmploiController@listeOffresEmployeur");

Route::get('/afficherOffre/{idOffre}', "OffreEmploiController@afficherOffre")->name('offre');

Route::post('/creerOffreEmploi', "OffreEmploiController@creerOffreEmploi");

Route::get('/creerOffreEmploi', "OffreEmploiController@afficherCreationOffre")->name('creerOffre');

Route::post('/modifOffreEmploi/{idOffre}', "OffreEmploiController@modifOffreEmploi");

//Route de test pour le front
Route::get('testInterface','TestInterfaceController@index');


/**
*Route victor
*
*/

Route::get('/modifOffreEmploi/{idOffre}', "OffreEmploiController@afficherModifOffre")->name("modifOffre");

Route::get('/candidater/{idOffre}',"CandidatureController@afficherCreationCandidater")->name("candidature");

Route::post('/candidater/{idOffre}',"CandidatureController@candidaterOffre")->name("candidaturePost");

Route::get('/notifications',"CompteControleur@getListesInteraction")->name("notifications");

Route::get('/listeCandidates/{idOffre}',"CandidatureController@avoirListeCandidat")->name('listeCandi');

Route::post('/listeCandidates/{idOffre}',"CandidatureController@modifierEtat");

Route::get('/rechercher',"OffreEmploiController@rechercheOffreEmploi")->name("rechercher");


/*
*
*
*     ROUTES A MAEL !
*
*
*
*/
//Routes carte
Route::get('Carte/{type}','CarteController@index')->name("Carte");

Route::get('/offre/marqueur/{type}/{id?}','CarteController@getMarqueur')->name("offre.JSON");

Route::get('/Covoiturage', "CovoiturageController@index")->name("Covoiturage");

site/resources/views/admin/index.blade.php
@extends('layouts.template')

@section('style')
    @parent
    <link rel='stylesheet' href='{{ url('/')}}/css/admin.css'>
@endsection

@section('contenu')
<h1>Bonjour {{$user->prenom}}</h1>

@if(session("erreur"))
    <div class='alert alert-danger w-100 text-center'>
        {{session("erreur")}}
    </div>
@elseif(session("message"))
    <div class='alert alert-success w-100 text-center'>
        {{session("message")}}
    </div>
@endif

<h2 class='mt-5'>Statistiques du site</h2>
  <div class="row py-5">
      <div class="col-12 col-lg-6">
          <canvas id='offres-candidatures' data-fetch-url="{{route('admin.stats.candidatures')}}"></canvas>
      </div>
      <div class="col-12 col-lg-6" style='position:relative'>
          <div id='numberStats' data-fetch-url="{{route('admin.stats.numbers')}}" class='row'>
              <div class='col-4 col-md-4'><div id='nbUsers' class='number'>0</div>utilisateurs</div>
              <div class='col-4 col-md-4'><div class='number' id='nbCandidatures'>0</div>candidatures</div>
              <div class='col-4 col-md-4'><div class='number' id='nbOffresEmplois'>0</div>offres d'emploi</div>
              <div class='col-4 col-md-4'><div class='number' id='nbCandidaturesAcceptees'>0</div>emplois trouvés</div>
              <div class='col-4 col-md-4'><div class='number' id='nbCovoiturage'>0</div>covoiturages</div>
              <div class='col-4 col-md-4'><div class='number' id='nbEmployeurs'>0</div>employeurs</div>
          </div>
      </div>
    </div>

    <h2 class='mt-5'>Modification des catégories d'activité</h2>
     <div class="row py-5">
         <div class='table-responsive'>
             <table class='table w-100'>
                 <thead>
                     <tr>
                         <th>Nom</th>
                         <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($categories as $cat)
                        <tr>
                            <td>{{$cat->nom}}</td>
                            <td>
                                <form action='{{route("admin.categories.destroy", $cat)}}' method='post'>
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class='btn btn-danger'>&times</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class='col-12'>
            <h3 class='my-5'>Ajouter une catégorie</h3>
            <form method='POST' class='form-row' action='{{route("admin.categories.store")}}'>
                {{csrf_field()}}
                <div class='col-12 col-sm-9'>
                    <input class='form-control' type='text' name='nom' placeholder='Nom de la catégorie'>
                </div>
                <div class='col-12 col-sm-3'>
                    <button class='btn btn-primary'>Ajouter</button>
                </div>
            </form>
        </div>
     </div>


@endsection

@section('js')
    @parent
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" integrity="sha256-oSgtFCCmHWRPQ/JmR4OoZ3Xke1Pw4v50uh6pLcu+fIc=" crossorigin="anonymous"></script>
    <script src="{{ url('/')}}/js/admin.js"></script>

@endsection